backend:
  name: github
  branch: master
  repo: bjpirt/next.recipes.pirt.co.uk
media_folder: public/img
public_folder: img
site_url: https://epic-goldwasser-a458e9.netlify.app
collections:
  - name: recipes
    create: true
    label: recipes
    folder: _collections/recipes
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", valueField: "name", searchFields: ["name"], multiple: false}
      - {label: "Images", name: "images", required: false, widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Source", name: "source", required: false, widget: "markdown"}
      - {label: "Tags", collapsed: false, name: "tags", required: false, widget: "relation", collection: "tags", valueField: "name", searchFields: ["name"], multiple: true}
      - {label: "Cuisine", name: "cuisine", required: false, widget: "relation", collection: "cuisines", valueField: "name", searchFields: ["name"], multiple: false}
      - {label: "Serves", name: "serves", required: false, widget: "string"}
      - {label: "Ingredients", collapsed: false, name: "ingredients", widget: "list", field: {label: "Ingredient", name: "ingredient", widget: "string"}}
      - {label: "Method", collapsed: false, name: "method", widget: "list", field: {label: "Step", name: "step", widget: "markdown"}}
  - name: categories
    create: true
    label: categories
    folder: _collections/categories
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
  - name: cuisines
    create: true
    label: cuisines
    folder: _collections/cuisines
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
  - name: tags
    create: true
    label: tags
    folder: _collections/tags
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
