backend:
  name: github
  branch: master
  repo: bjpirt/next.recipes.pirt.co.uk
media_folder: public/img
public_folder: img
site_url: https://epic-goldwasser-a458e9.netlify.app
collections:
  - name: recipes
    create: true
    label: recipes
    folder: recipes
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Source", name: "source", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Cuisine", name: "cuisine", widget: "string"}
      - {label: "Ingredients", name: "ingredients", widget: "list"}
      - {label: "Method", name: "method", widget: "list"}
