backend:
  name: github
  branch: master
  repo: bjpirt/next.recipes.pirt.co.uk
media_folder: public/img
public_folder: img
site_url: https://epic-goldwasser-a458e9.netlify.app
collections:
  - name: recipes
    create: true
    label: recipes
    folder: _collections/recipes
    fields:
      # - {label: "Test", name: "test", widget: "relation", collection: "recipes", valueField: "title", searchFields: ["title"], multiple: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Source", name: "source", widget: "string"}
      - {label: "Tags", collapsed: false, name: "tags", widget: "list", field: {label: "Value", name: "value", widget: "string"}}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Cuisine", name: "cuisine", widget: "string"}
      - {label: "Ingredients", collapsed: false, name: "ingredients", widget: "list", field: {label: "Ingredient", name: "ingredient", widget: "string"}}
      - {label: "Method", collapsed: false, name: "method", widget: "list", field: {label: "Step", name: "step", widget: "string"}}
